### PR TITLE
Add eval logic for tabular AMLB runs

### PR DESCRIPTION
**Pull request by gidler**
Description of changes:

This PR introduces evaluation logic from innixma's autogluon-benchmark repository into autogluon-bench.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gidler** [comment]
Once we determine if these are suitable eval changes, before merge I will update the README.md section about evaluation steps.

**Review by Innixma — APPROVED** [review]
Tested and it works correctly

**Review by Innixma — APPROVED** [review]
README updates LGTM

**Review by yinweisu — APPROVED** [review]
README looks good to me! Thanks for the work!

**Review by suzhoum — APPROVED** [review]
LGTM! Thanks for all the work!

**Pull request merged**
